### ISSUE TITLE
FireBase access error

### ISSUE THREAD

**Issue by PatalJunior-zz** [epifano-x/BOT-DISCORD-WL-AUTOMATICO-POR-ASYNC-REACT#2]
Ele está a dar erro a conectar com a firebase se não me engano

Edit: As credencias da firebase estão todas iguais no index.js, ele dá erro quando eu clico no emote para começar a WL automática

Aqui vai o erro
```javascript
(node:21916) UnhandledPromiseRejectionWarning: Error: permission_denied at /Servidores/levels/586943057447092245: Client doesn't have permission to access the desired data.
    at errorForServerCode (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:654:17)
    at onComplete (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:9088:33)
    at Object.onComplete (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:12664:34)
    at C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:11793:32
    at PersistentConnection.onDataMessage_ (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:12038:17)
    at Connection.onDataMessage_ (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:11352:14)
    at Connection.onPrimaryMessageReceived_ (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:11346:18)
    at WebSocketConnection.onMessage (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:11247:27)
    at WebSocketConnection.appendFrame_ (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:10835:18)
    at WebSocketConnection.handleIncomingFrame (C:\Users\eduar\Desktop\WLBOT\node_modules\@firebase\database\dist\index.node.cjs.js:10886:22)
(node:21916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
---------------------------------

Print da config da firebase

![image](https://user-images.githubusercontent.com/39913166/84842172-5d6a5f00-b03c-11ea-98d8-10c0bacd23c0.png)

**Comment by epifano-x** [comment]
utiliza ela como teste  pois como estavel ela tem esse rpbçema ai vc vai ter q muda os tratamentos de autenticaçao da mesma
